config/routes.rb
Rails.application.routes.draw do
root 'products#index'
get 'shopping_carts/:id' => 'shopping_carts#show'
delete 'shopping_carts/:id' => 'shopping_carts#destroy'
resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_one_attached :image
  has_many :product_shopping_carts, dependent: :destroy
  has_many :shopping_carts, through: :product_shopping_carts
  
  validates :category, presence: true
            enum category: { paintings: 0, photo_prints: 1, sculptures: 2 }

  validates :category, inclusion: { in: %w(paintings photo_prints sculptures),
            message: '%<value>s is not a valid type of product' }

  validates :name, presence: true, length: { maximum: 50 }
  validates :price, presence: true, 
            numericality: true, numericality: { only_float: true, greater_than: 0 } 

  validates :description, presence: true, length: { maximum: 250 }

  validate :acceptable_image?

  def acceptable_image?
    return unless image.attached?

    unless image.blob.byte_size <= 1.megabyte
      errors.add(:image, "The size of the image is too big")
    end

    acceptable_types = ["image/jpeg", "image/png"]
      unless acceptable_types.include?(image.content_type)
        errors.add(:image, "The image must be JPEG or PNG")
      end
  end

  scope :sort_by_name, -> { order(name: :desc) }
end

app/models/product_shopping_cart.rb
class ProductShoppingCart < ApplicationRecord
  belongs_to :product
  belongs_to :shopping_cart
end

app/models/product_user.rb
class ProductUser < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :product_shopping_carts, dependent: :destroy
  has_many :products, through: :product_shopping_carts
end

app/models/user.rb
# frozen_string_literal: true
require 'bcrypt'

class User < ApplicationRecord
  has_one :shopping_cart
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  
  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true, length: { maximum: 250 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 5, maximum: 15 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_shopping_cart, :current_customer

  private

  def current_customer
    if session[:user_id]
      @customer = User.find(session[:user_id])
    end
  end

  def current_shopping_cart
    if login?
      @current_shopping_cart = @customer.shopping_cart
    elsif session[:shopping_cart_id]
      @current_shopping_cart = ShoppingCart.find(session[:shopping_cart_id])
    else
      @current_shopping_cart = ShoppingCart.create
      session[:shopping_cart_id] = @current_shopping_cart.id
    end
  end

  def login?
    current_customer
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.sort_by_name
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
      flash[:success] = "New product has been created!"
    else
      render :new, status: :unprocessable_entity
      flash[:danger] = "Error. Please provide all necessary information to create a new product"
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:success] = "The Product has been updated!"
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
      flash[:danger] = "Something went wrong. Product's information has not been updated "
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.delete
    redirect_to products_path
    flash[:success] = "Product has been deleted"
  end

  private

  def product_params
    params.require(:product).permit(:name, :category, :price, :description, :image)
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  def show
    @cart = @current_shopping_cart
  end

  def destroy
    @cart = @current_shopping_cart
    @cart.destroy
    session[:shopping_cart_id] = nil
    redirect_to root_path
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |message_type, message| %>
    <div>
    <%= message %>
    </div>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<% render "flash" %>

<h1> Edit Product </h1>

<%= form_with model: @product do |form| %>
  <div>
    <%= form.label :product_image %><br>
    <%= form.file_field :image %>
  </div>
  
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :category %><br>
    <%= form.select :category, Product.categories.keys %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/index.html.erb
<%= render "flash" %>

<h1> Products </h1>
  <p> Discover & Buy Exclusive Art from Poland designed and created by artist Alicja Kucharska! </p>
<ul>
  <% @products.each do |product| %>
    <li>
      <%= product.name %>
      <%= product.category %>
        <% if product.image.attached? %>
          <%= image_tag product.image.variant(resize_to_limit: [150, 150]) %> 
        <% end %>
    </li>
     <%= button_to "Add #{product.name} to the cart" %>
  <% end %>
</ul>

app/views/products/new.html.erb
<%= render "flash" %>

<h1> New Product </h1>

<%= form_with model: @product do |form| %>
  <div>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </div>
  
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :category %><br>
    <%= form.select :category, Product.categories.keys %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/show.html.erb
<%= render "flash" %>

<h1><%= @product.name %></h1>
<p><%= @product.price %></p>
<p><%= @product.description %></p>
<p><%= @product.category %></p>
<% if @product.image.attached? %>
  <p><%= image_tag @product.image.variant(resize_to_limit: [150, 150]) %> 
  <% end %></p>

<ul>
  <li><%= link_to "Edit", edit_product_path(@product) %></li>
  <li><%= button_to "Destroy", @product, method: :delete %></li>
</ul>

app/views/shopping_carts/show.html.erb
<h1> Shopping Cart show </h1>
<ul>
  <% @cart.products.each do |product| %>
    <%= product.name %> 
  <% end %>
</ul>